### ISSUE TITLE
Các bug trong Key Results

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-api#150]
**Describe the bug**
- Target value phải > 0 và lớn hơn current Value
- Links là array, trong nghiệp vụ là chỉ chứa 2: 1 là link công việc, 2 là link kết quả

**Screenshots**
![image](https://user-images.githubusercontent.com/24296018/89023283-870dea00-d34d-11ea-9e9e-1b24faa2282b.png)

**Comment by quangnv281098** [comment]
tạo thêm một colum link mới chứ việc gì phải đưa nó vào 1 mảng làm gì

**Comment by harrytran998** [comment]
> tạo thêm một colum link mới chứ việc gì phải đưa nó vào 1 mảng làm gì

Thế scale nghiệp vụ lên thì có tầm 4 columns --> tầm 500 records thì, mà k phải cái nào cũng có --> Null nhiều
Thiết kế DB ưu tiên horizontal hơn là vertical nhé!
