### ISSUE TITLE
Không tạo được OKRs

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-api#151]
**Describe the bug**
T thử tạo OKRs root thì không tạo được, nó cứ báo lỗi thao tác với DB

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24296018/89024119-cf79d780-d34e-11ea-8b60-3fec4148e139.png)
## Ở DB thông báo như này
![image](https://user-images.githubusercontent.com/24296018/89024134-d56fb880-d34e-11ea-879b-63c5db676057.png)

**Comment by quangnv281098** [comment]
cái này t đang để lúc add vào database thì phải add đầy đủ column, lát nữa t sửa, giờ tạm thời m cứ insert vào tất cả các column xem có lỗi không đã
